// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnzbwurtojhickalchot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuemJ3dXJ0b2poaWNrYWxjaG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTIwMjksImV4cCI6MjA1OTY4ODAyOX0.mhm0xf4nbG5rC70t2BcJRg0kh98xaTv6vhKWL4TxdwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);